a = int(input("Enter first integer: "))
b = int(input("Enter second integer: "))
print("AND:", a & b)
print("OR:", a | b)
print("XOR:", a ^ b)
print("NOT of first:", ~a)
print("Left shift first:", a << 1)
print("Right shift first:", a >> 1)
